# This file contains configuration flags to customize your site

# Name of your site (displayed in the header)
name: ronin4n6labs

# Short bio or description (displayed in the header)
description: "Ronin Forensic Researcher's Notebook"

# URL of your avatar or profile pic (optional)
avatar:  # Leave blank or add your own URL, e.g., https://github.com/ronin4n6labs.png

# Your website URL
url: "https://ronin4n6labs.github.io"

# Footer links (customize or leave blank)
footer-links:
  dribbble:
  email: # your.email@example.com
  facebook:
  flickr:
  github: ronin4n6labs
  instagram:
  linkedin:
  pinterest:
  rss: yes  # Enables RSS icon
  twitter: # your_twitter_handle
  stackoverflow:
  youtube:
  googleplus:

# Optional: Disqus or Google Analytics
disqus:
google_analytics:

# Baseurl (leave empty for user repo like yours)
baseurl: ""

# Permalink style
permalink: /:title/

# Jekyll Now version
version: v1.2.0

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass settings
sass:
  style: expanded

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from production
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
